platform :ios, '12.1'
use_frameworks!

target 'uberribs' do

    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'    
    pod 'SnapKit', '~> 4.0.0'
    pod 'RIBs', :git => 'https://github.com/uber/RIBs.git', :branch => 'master'

end
